import { writeFileSync } from "fs";
import { noteLifecycleMermaid } from "src/services/notes/lifecycle";
import {
  syncDecisionTableMarkdown,
  syncDecisionTableMarkdownCommandCentric,
  syncDecisionTableMermaid,
} from "src/services/notes/decision-table";

const doc = `# Note Lifecycle State Machine & Decision Tables

> This document is generated from source code. Do not edit manually.
> Run \`pnpm run doc:state-machine\` to regenerate.

## 1. State Machine Topology

**Location:** \`src/services/notes/lifecycle.ts:47-79\`  
**11 states, 13 events, ~30 transitions**

This is the **single source of truth** for legal state transitions. The xstate machine, Mermaid diagram, and runtime validation all derive from this table.

\`\`\`mermaid
${noteLifecycleMermaid().replace(/\(/g, "<br/>").replace(/\)/g, "")}
\`\`\`

## 2. Decision Tables — Command Policies

**Location:** \`src/services/notes/decision-table.ts\`  
**1 canonical decision × 11 states, projected into 3 command tables = 33 rows**

This is the **second independent authority**. One canonical table per state defines what each command (import/export/sync) does in that state — which event to emit, whether force changes it, which component is responsible, and why. The three command tables are derived from it at runtime.

### 1. Export Wizard (force: Obsidian wins)

\`\`\`mermaid
${syncDecisionTableMermaid("export")}
\`\`\`

### 2. Import Wizard (force: Anki wins)

\`\`\`mermaid
${syncDecisionTableMermaid("import")}
\`\`\`

### 3. Sync Command (no force)

\`\`\`mermaid
${syncDecisionTableMermaid("sync")}
\`\`\`

#### Decision Table (Markdown) — State-Centric (Transposed)

${syncDecisionTableMarkdown()}

<details>
<summary>Command-Centric Tables (per command)</summary>

${syncDecisionTableMarkdownCommandCentric()}

</details>

---

*Generated by \`pnpm run doc:state-machine\` from \`src/dev/print-state-machine.ts\`*
`;

writeFileSync("docs/state-machine.md", doc);
